language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - 1.49.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo install cargo-tarpaulin -f
  fi
before_script:
- rustup component add rustfmt
# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo clean &&
  cargo fmt --all -- --check &&
  cargo build &&
  cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --run-types Tests Doctests --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
